#!/usr/bin/env bash

package=$1
available=$(find . -mindepth 1 -maxdepth 1 -type d -printf '%f\n' | grep -v '\.')

if ! [[ -n $package ]]; then
	echo "No package choosen, aborting..."
	exit 1
fi

if ! [[ ${available[*]} =~ "$package" ]]; then
	echo "Package ${package} not found, aborting..."
	echo "The following packages are available:"
	echo "${available[@]}"
	exit 1
fi

cd "${package}/"

echo "Building ${package}..."

makepkg --syncdeps --force --install --noconfirm

/usr/bin/env bash
